mlpcre/pcre-c.c: Remove unused variable
On macOS:

pcre-c.c:281:22: error: unused variable 'str' [-Werror,-Wunused-variable]
  CLEANUP_FREE char *str = NULL;
                     ^