mltools/tools_utils-c.c: Free keystore after decryption
Note that free_key_store was previously defined but never used.  As
far as I can see the keystore and keys are not used after calling
inspect_do_decrypt so this should be safe.  I also tested it on an
encrypted guest.

Found by Coverity:

  Error: RESOURCE_LEAK (CWE-772): [#def13] [important]
  virt-v2v-2.0.4/common/mltools/tools_utils-c.c:84: alloc_fn: Storage is returned from allocation function "key_store_import_key".
  virt-v2v-2.0.4/common/mltools/tools_utils-c.c:84: var_assign: Assigning: "ks" = storage returned from "key_store_import_key(ks, &key)".
  virt-v2v-2.0.4/common/mltools/tools_utils-c.c:89: noescape: Resource "ks" is not freed or pointed-to in "inspect_do_decrypt".
  virt-v2v-2.0.4/common/mltools/tools_utils-c.c:91: leaked_storage: Variable "ks" going out of scope leaks the storage it points to.
  #   89|     inspect_do_decrypt (g, ks);
  #   90|
  #   91|->   CAMLreturn (Val_unit);
  #   92|   }
  #   93|