mlstdutils/std_utils.ml: Fix for OCaml 4.12.
We were using a default function from somewhere called "compare"
instead of the actual function (Pervasives.compare / Stdlib.compare).
Since the wrong default function was used it had a different type from
what we expected:

File "std_utils.ml", line 312, characters 36-37:
312 |       | (y, y') :: _ when cmp x y = 0 -> y'
                                          ^
Error: This expression has type int but an expression was expected of type
         'weak1 list -> int