windows/windows.c: Remove ignore -Wanalyzer-null-argument
Added in 2021 to work around a GCC 11 analyzer warning which is fixed
upstream.

On macOS (clang):

windows.c:62:32: error: unknown warning group '-Wanalyzer-null-argument', ignored [-Werror,-Wunknown-warning-option]
                               ^